version: '3.8'

services:
  web:
    build: .
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yamdb_user
      - POSTGRES_PASSWORD=yamdb_pass
      - POSTGRES_DB=yamdb_db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    
volumes:
  postgres_data:
  static_volume:
